### ISSUE TITLE
Uses localhost instead of endpoints: value

### ISSUE THREAD

**Issue by maxmannen** [SquashConsulting/ecto_aql#5]
This might be an error from me as relative new to Phoenix/Elixir:
It seems a connection with localhost is made despite I have changed the config:
config :arango_lnodes, ArangoLnodes.Repo,
  username: 'root',
  password: 'pass',
  endpoints: 'http://xx.xx.xxx.xxx:8529',
  pool_size: 10,
  database: "mydatabase",
  show_sensitive_data_on_connection_error: true
If I use the above in an Iex-session I get a connection. If I do something wrong with the endpoints: value I get an error (like missing port) which means it is beeing read. Edit: also password field is not read. 
Am I missing something here or is this a bug?

**Comment by maxmannen** [comment]
Endpoints should be in brackets. Its Aragox that doesnt give an error...

**Comment by rasjonell-zz** [comment]
Hey @maxmannen, so passing your external endpoint as a list solves the issue?
From Arangox [source code](https://github.com/ArangoDB-Community/arangox/blob/master/lib/arangox.ex#L68) seems like `endpoints` can be either a list of endpoints or just a binary,
did you pass your endpoint string with a single quote? If yes, then that may be a problem as in Elixir single quoted strings are lists wherease double-quoted ones are binaries. You can check that in iex:
```elixir
 λ iex | 1 | ▶▶ i "http://localhost:8529"
Term
  "http://localhost:8529"
Data type
  BitString
Reference modules
  String, :binary


 λ iex | 2 | ▶▶ i 'http://localhost:8529'
Term
  'http://localhost:8529'
Data type
  List
Reference modules
  List
```

```elixir
* `:endpoints` - Either a single _ArangoDB_ endpoint binary, or a list of endpoints in
    order of presedence. Each process in a pool will individually attempt to establish a connection
    with and check the availablility of each endpoint in the order given until an available endpoint
    is found. Defaults to `"http://localhost:8529"`.
```

There is also an option to pass a callback to catch connection failures:

```elixir
* `:failover_callback` - A function to call every time arangox fails to establish a
    connection. This is only called if a list of endpoints is given, regardless of whether or not
    it's connecting to an endpoint in an _active failover_ setup. Can be either an anonymous function
    that takes one argument (which is an `%Arangox.Error{}` struct), or a three-element tuple
    containing arguments to pass to `apply/3` (in which case an `%Arangox.Error{}` struct is always
    prepended to the arguments).
```

Hope this helps.

**Comment by maxmannen** [comment]
Thanks again. Very helpful
